Resources:
  SaveForLaterDynamoTable:
    DeletionPolicy: Retain
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - KeyType: HASH
          AttributeName: userId
      TableName: !Sub '${App}-${Stage}-articles'
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      ProvisionedThroughput:
        WriteCapacityUnits: !FindInMap
          - StageVariables
          - !Ref Stage
          - TableWriteCapacity
        ReadCapacityUnits: !FindInMap
          - StageVariables
          - !Ref Stage
          - TableReadCapacity
Description: Implements save for later for mobile
Parameters:
  DynamoNotificationTopic:
    Type: String
    Description: SNS topic to notify when there's a dynamo throttling event
  App:
    Default: mobile-save-for-later
    Type: String
    Description: Application name
  Stage:
    Type: String
    Description: Stage name
    AllowedValues:
      - CODE
      - PROD
Mappings:
  StageVariables:
    CODE:
      TableReadCapacity: 1
      TableWriteCapacity: 1
    PROD:
      TableReadCapacity: 200
      TableWriteCapacity: 75
