Resources:
  SaveForLaterWriteThrottleEvents:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: !Ref SaveForLaterDynamoTable
      AlarmActions:
        - !Ref DynamoNotificationTopic
      Namespace: AWS/DynamoDB
      Period: 60
      ComparisonOperator: GreaterThanThreshold
      AlarmName: !Sub '${App}-${Stage}-articles-WriteCapacityUnitsLimit-BasicAlarm'
      ActionsEnabled: !FindInMap
        - StageVariables
        - !Ref Stage
        - AlarmActionsEnabled
      Statistic: Sum
      Threshold: 0
      Unit: Count
      MetricName: WriteThrottleEvents
  SaveForLaterReadThrottleEvents:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: !Ref SaveForLaterDynamoTable
      AlarmActions:
        - !Ref DynamoNotificationTopic
      Namespace: AWS/DynamoDB
      Period: 60
      ComparisonOperator: GreaterThanThreshold
      AlarmName: !Sub '${App}-${Stage}-articles-ReadCapacityUnitsLimit-BasicAlarm'
      ActionsEnabled: !FindInMap
        - StageVariables
        - !Ref Stage
        - AlarmActionsEnabled
      Statistic: Sum
      Threshold: 0
      Unit: Count
      MetricName: ReadThrottleEvents
  SaveForLaterDynamoTable:
    DeletionPolicy: Retain
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - KeyType: HASH
          AttributeName: userId
      TableName: !Sub '${App}-${Stage}-articles'
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      ProvisionedThroughput:
        WriteCapacityUnits: !FindInMap
          - StageVariables
          - !Ref Stage
          - TableWriteCapacity
        ReadCapacityUnits: !FindInMap
          - StageVariables
          - !Ref Stage
          - TableReadCapacity
Description: Implements save for later for mobile
Parameters:
  DynamoNotificationTopic:
    Type: String
    Description: SNS topic to notify when there's a dynamo throttling event
  App:
    Default: mobile-save-for-later
    Type: String
    Description: Application name
  Stage:
    Type: String
    Description: Stage name
    AllowedValues:
      - CODE
      - PROD
Mappings:
  StageVariables:
    CODE:
      AlarmActionsEnabled: false
      TableReadCapacity: 1
      TableWriteCapacity: 1
    PROD:
      AlarmActionsEnabled: true
      TableReadCapacity: 200
      TableWriteCapacity: 75