name: CI
on: push

jobs:
  mobile-save-for-later-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Setup JDK and sbt
        uses: guardian/setup-scala@v1

      - name: Run Tests and Create Artifacts
        run: sbt "project mobile-save-for-later" test assembly

      - name: Build CDK
        working-directory: ./cdk
        run: |
          yarn install
          yarn lint
          yarn test
          yarn synth

      - name: RiffRaff upload artifacts and upload cfn
        uses: guardian/actions-riff-raff@v2
        with:
          app: mobile-save-for-later
          configPath: ./mobile-save-for-later/riff-raff.yaml
          contentDirectories: |
            mobile-save-for-later-cfn:
              - cdk/cdk.out/MobileSaveForLater-CODE.template.json
              - cdk/cdk.out/MobileSaveForLater-PROD.template.json
            mobile-save-for-later:
             - mobile-save-for-later/target/scala-2.13/mobile-save-for-later.jar
